### ISSUE TITLE
Linting breaks on TravisCI

### ISSUE THREAD

**Issue by icemac** [zopefoundation/Products.ZSQLMethods#27]
On current master the lint job on TravisCI is not successful. This might be because of newer package versions used.
I activated weekly builds so in future we could notice this earlier.

See https://travis-ci.org/github/zopefoundation/Products.ZSQLMethods/jobs/707796714

**Comment by dataflake** [comment]
You're correct, this is due to `isort` version 5, which breaks/complains on the following (and which will happen to pretty much all our packages):

- using `--recursive` in `tox.ini`
- using `not_skip` in `setup.cfg`
- it now peeks into functions and methods and sees imports there
- it breaks `flake8` if the plugin `flake8-isort` is used. Why that's used in many places I dont't know - we already run `isort` separately in most places I know.

**Comment by dataflake** [comment]
Fixed by 9679eb0f14ef352e27e3263011c02c828dfc5346 and 97c3c2de9cf0a10d29c5e8f858095a8977b39900

**Comment by icemac** [comment]
Thank you!
